---
- name: Install libselinux-python
  yum: name=libselinux-python state=present
  
- name: Copy Epel Release
  copy: src=epel-release-6-8.noarch.rpm dest=/root
  
- name: Copy Remi Release
  copy: src=remi-release-6.rpm dest=/root
  
- name: Install Remi and Epel
  shell: chdir=/root rpm -Uvh remi-release-6*.rpm
  
- name: Copy the EPEL repository definition
  copy: src=remi.repo dest=/etc/yum.repos.d/remi.repo